class Config:
    # Fixed task dimensions.
    TASK_NAME = "ObstacleHover"
    OBS_DIM = 95
    ACTION_DIM = 4
    MAX_WAYPOINTS = 8
    OBSTACLE_FEATURE_DIM = 32
    TIME_ENCODING_DIM = 4

    # Training hyperparameters.
    LEARNING_RATE = 0.0005
    CLIP_PARAM = 0.1
    GAMMA = 0.995
    LAM = 0.95
    VALUE_LOSS_COEF = 0.5
    ENTROPY_COEF = 0.001
    MAX_GRAD_NORM = 10.0

    # Training schedule.
    NUM_LEARNING_EPOCHS = 4
    NUM_MINI_BATCHES = 16
    NUM_STEPS_PER_ENV = 64
    MODEL_SAVE_INTERVAL_SEC = 180

    # Model architecture.
    ACTOR_HIDDEN_DIMS = [256, 128, 64]
    CRITIC_HIDDEN_DIMS = [256, 128, 64]
    ACTIVATION = "elu"
    INIT_NOISE_STD = 1.0
    FIXED_STD = False

    # Reward coefficients.
    REWARD_DISTANCE_SCALE = 0.6
    DISTANCE_REWARD_MULTIPLIER = 6.0
    GOAL_REACHED_REWARD = 100.0
    IN_ARENA_REWARD = 0.0
    OUT_OF_ARENA_PENALTY = 100.0

    # Hierarchical control switches.
    USE_HIERARCHICAL = True
    USE_RULE_MPC = True
    DIRECT_GOAL_MODE = False
    STRAIGHT_LINE_MODE = False
    HOVER_TEST = False
    PARAM_TEST = False

    # Strict linear MPC.
    MPC_DT = 0.02
    MPC_HORIZON = 12
    MPC_CONTROL_HORIZON = 12
    MPC_HOVER_HORIZON = 18

    MPC_Q_POS_XY = 20.0
    MPC_Q_VEL_XY = 5.0
    MPC_R_U_XY = 0.08
    MPC_R_DU = 0.65
    MPC_A_MAX_XY = 3.375

    MPC_Q_POS_Z = 28.0
    MPC_Q_VEL_Z = 5.0
    MPC_R_U_Z = 0.10
    MPC_R_DU_Z = 0.55
    MPC_A_MAX_Z = 5.4

    MPC_HOVER_Q_POS_XY = 150.0
    MPC_HOVER_Q_VEL_XY = 14.0
    MPC_HOVER_R_U_XY = 0.02
    MPC_HOVER_R_DU = 0.35
    MPC_HOVER_Q_POS_Z = 180.0
    MPC_HOVER_Q_VEL_Z = 15.0
    MPC_HOVER_R_U_Z = 0.025
    MPC_HOVER_R_DU_Z = 0.25

    MPC_GRAVITY = 9.81
    MPC_MAX_ROLL_RAD = 0.405
    MPC_MAX_PITCH_RAD = 0.405
    MPC_ATT_KP_ROLL = 2.4
    MPC_ATT_KP_PITCH = 2.4
    MPC_ATT_KD_ROLL = 0.18
    MPC_ATT_KD_PITCH = 0.18
    MPC_MAX_ROLL_RATE = 0.945
    MPC_MAX_PITCH_RATE = 0.945
    MPC_THRUST_GAIN = 0.08775
    MPC_THRUST_MIN = -0.25
    MPC_THRUST_MAX = 0.25
    MPC_TARGET_XY_CLIP = 2.50
    MPC_TARGET_Z_CLIP = 1.20
    MPC_STARTUP_FRAMES = 24
    MPC_STARTUP_MIN_XY_SCALE = 1.00
    MPC_STARTUP_MIN_Z_SCALE = 1.00
    MPC_XY_ENABLE_Z_ERR = 0.35
    MPC_XY_HIGH_Z_SCALE = 0.60
    MPC_TAKEOFF_MIN_FRAMES = 18
    MPC_TAKEOFF_STRONG_ALT = 0.10
    MPC_TAKEOFF_RELEASE_ALT = 0.32
    MPC_TAKEOFF_XY_ACCEL_LIMIT_STRONG = 0.16
    MPC_TAKEOFF_XY_ACCEL_LIMIT = 1.6875
    MPC_TAKEOFF_MAX_TILT_RAD = 0.2025
    MPC_TAKEOFF_STRONG_TILT_RAD = 0.026
    MPC_TAKEOFF_XY_SLEW_LIMIT = 0.035
    MPC_XY_SLEW_LIMIT = 0.55
    MPC_XY_SLEW_LIMIT_DENSE = 0.37125
    MPC_TAKEOFF_Z_SLEW_LIMIT = 0.30375
    MPC_Z_SLEW_LIMIT = 0.85
    MPC_Z_SLEW_LIMIT_DENSE = 0.675
    MPC_HOVER_THRUST_BIAS = 0.0
    MPC_STARTUP_THRUST_BIAS = 0.012
    MPC_VZ_DAMP = 0.14
    MPC_GOAL_HOVER_VZ_DAMP = 0.28
    MPC_GOAL_HOVER_THRUST_BIAS = 0.0
    MPC_GOAL_BIAS_DIST_XY = 0.35
    MPC_GOAL_BIAS_DIST_Z = 0.25
    MPC_GOAL_BIAS_SPEED_XY = 0.30
    MPC_GOAL_BIAS_SPEED_XY_DENSE = 0.24
    MPC_WP_REACHED_XY = 0.18
    MPC_WP_REACHED_Z = 0.20
    MPC_WP_REACHED_SPEED_XY = 0.30
    MPC_WP_HOLD_STEPS = 12
    MPC_WP_PASS_THROUGH_ENABLE = True
    MPC_WP_PROFILE_MIN_SPEED = 0.28
    MPC_WP_PROFILE_MAX_SPEED_BASE = 0.45
    MPC_WP_PROFILE_MAX_SPEED_GAIN = 0.42
    MPC_WP_PROFILE_MAX_SPEED_CAP = 1.35
    MPC_WP_PROFILE_ACCEL_FRAC = 0.25
    MPC_WP_PROFILE_DECEL_FRAC = 0.25
    MPC_WP_PROFILE_FINISH_SPEED_FRAC = 0.32
    MPC_WP_PROFILE_FINAL_FINISH_SPEED_FRAC = 0.60  # final waypoint: carry momentum toward goal
    MPC_WP_PREVIEW_ENABLE = True
    MPC_WP_PREVIEW_DIST = 0.55
    MPC_WP_PREVIEW_BLEND_MAX = 0.22
    MPC_WP_PREVIEW_MIN_NEXT_DIST = 0.20
    MPC_WP_Z_SYNC_ENABLE = True
    MPC_WP_Z_REF_SPEED_MAX = 0.85
    MPC_WP_Z_NEAR_XY_DIST = 0.25
    MPC_WP_Z_NEAR_ERR = 0.12
    MPC_WP_Z_NEAR_XY_SPEED_SCALE = 0.35
    MPC_DANGER_WP_ENABLE = True
    MPC_DANGER_WP_CLEARANCE = 0.25
    MPC_DANGER_WP_STOP_SPEED = 0.08
    MPC_DANGER_WP_HOLD_FRAMES = 8
    MPC_DANGER_SEGMENT_ENABLE = True
    MPC_DANGER_SEGMENT_CLEARANCE = 0.35
    MPC_DANGER_SEGMENT_HARD_CLEARANCE = 0.08
    MPC_DANGER_SEGMENT_RISK_WEIGHT = 8.0
    MPC_DANGER_SEGMENT_HARD_PENALTY = 40.0

    # ---------------------------------------------------------------------------
    # Dense-obstacle (3+) MPC: danger / critical / late-waypoint logic
    # ---------------------------------------------------------------------------
    MPC_CRITICAL_WP_CLEARANCE = 0.10
    MPC_DANGER_WP_CLEARANCE_DENSE = 0.35
    MPC_DANGER_WP_APPROACH_SPEED_SCALE = 0.75
    MPC_DANGER_WP_BRAKE_DIST_FRAC = 0.33
    MPC_DANGER_WP_BRAKE_ACCEL_SCALE = 1.15
    MPC_DANGER_SEGMENT_SPEED_SCALE = 0.55
    MPC_SAFE_SEGMENT_SPEED_SCALE = 1.40
    MPC_LATE_WP_SAFE_FRAME = 1050
    MPC_FORCE_GOAL_FRAME = 1200
    MPC_SKIP_START_SIDE_FRAME = 950
    MPC_SKIP_START_SIDE_X = 2.0
    MPC_LATE_WP_ROUTE_EXTRA = 0.60
    MPC_LATE_WP_ROUTE_OVERSHOOT = 0.20

    # Dense-obstacle (3+) MPC: post-danger segment guard
    MPC_POST_DANGER_SEGMENT_GUARD_FRAMES = 45
    MPC_POST_DANGER_SEGMENT_CLEARANCE = 0.45
    MPC_POST_DANGER_SEGMENT_SPEED_SCALE = 0.45

    # Dense-obstacle (3+) MPC: segment detour avoidance
    MPC_SEGMENT_DETOUR_ENABLE = True
    MPC_SEGMENT_DETOUR_CLEARANCE = 0.35
    MPC_SEGMENT_DETOUR_EXTRA_MARGIN = 0.10
    MPC_SEGMENT_DETOUR_ADVANCE = 0.25
    MPC_SEGMENT_DETOUR_HOLD_FRAMES = 28
    MPC_SEGMENT_DETOUR_RADIUS_SCALES = [1.0, 1.35, 1.70]

    # Dense-obstacle (3+) MPC: hard safety (accel-level override)
    MPC_HARD_SAFETY_ENABLE = True
    MPC_HARD_SAFETY_CLEARANCE = 0.18
    MPC_HARD_SAFETY_RELEASE_CLEARANCE = 0.26
    MPC_HARD_SAFETY_AWAY_ACCEL = 2.4
    MPC_HARD_SAFETY_BRAKE_GAIN = 1.8
    MPC_HARD_SAFETY_MAX_ACCEL = 2.6

    # Dense-obstacle (3+) MPC: speed brake system
    MPC_SPEED_BRAKE_ENABLE = True
    MPC_SPEED_BRAKE_DECEL = 1.8
    MPC_SPEED_BRAKE_BUFFER = 0.18
    MPC_SPEED_BRAKE_DIST_MIN = 0.35
    MPC_SPEED_BRAKE_GAIN = 1.35
    MPC_SPEED_BRAKE_MAX_ACCEL = 1.8
    MPC_SPEED_BRAKE_NEAR_OBS_CLEARANCE = 0.65
    MPC_SPEED_BRAKE_NEAR_OBS_SPEED = 0.25
    MPC_SPEED_BRAKE_SAFE_SPEED = 0.55

    # Dense-obstacle (3+) MPC: goal-directed speed management
    MPC_GOAL_SPEED_ENABLE = True
    MPC_GOAL_FAST_DIST = 0.60
    MPC_GOAL_BRAKE_DIST = 0.45
    MPC_GOAL_PRECISE_DIST = 0.30
    MPC_GOAL_FAST_SPEED_SCALE = 1.25
    MPC_GOAL_BRAKE_SPEED_SCALE = 0.28

    # Local cylindrical obstacle avoidance. Cylinders are full-height, so avoid in x-y.
    OBSTACLE_AVOID_ENABLE = True
    OBSTACLE_LOOKAHEAD_MIN = 0.05
    OBSTACLE_LOOKAHEAD_MAX = 1.35
    OBSTACLE_LOOKAHEAD_MAX_DENSE = 1.00
    OBSTACLE_NORMAL_TRIGGER_MIN = 0.60
    OBSTACLE_BASE_MARGIN = 0.26
    OBSTACLE_SPEED_MARGIN_GAIN = 0.14
    OBSTACLE_SPEED_MARGIN_GAIN_DENSE = 0.08
    OBSTACLE_DETOUR_MARGIN = 0.42
    OBSTACLE_DETOUR_ADVANCE = 0.45
    OBSTACLE_AVOID_HOLD_FRAMES = 30
    OBSTACLE_AVOID_HOLD_FRAMES_DENSE = 18
    OBSTACLE_WALL_MARGIN = 0.32
    OBSTACLE_EMERGENCY_MARGIN = 0.40
    OBSTACLE_EMERGENCY_MARGIN_DENSE = 0.24
    OBSTACLE_EMERGENCY_GAIN = 2.2
    OBSTACLE_EMERGENCY_ACCEL_MAX = 1.8
    OBSTACLE_EMERGENCY_Z_CLIMB_GAIN = 0.25

    # Tangential force for obstacle avoidance (slides around obstacles).
    OBSTACLE_TANGENTIAL_GAIN = 0.65
    OBSTACLE_TANGENTIAL_MAX = 1.2

    # Arena boundary repulsion (prevents wall collisions in enclosed space).
    BOUNDARY_REPULSION_ENABLE = True
    BOUNDARY_REPULSION_MARGIN = 0.35
    BOUNDARY_REPULSION_GAIN = 2.5

    # Tangential direction lock (prevents figure-8 oscillation between obstacles).
    TAN_DIR_LOCK_ENABLE = True
    TAN_DIR_LOCK_MIN_FRAMES = 8

    # Attraction-source transition: smooth blend from detour back to original target.
    OBSTACLE_AVOID_TRANSITION_ENABLE = True
    OBSTACLE_AVOID_TRANSITION_BLEND = 0.55
    OBSTACLE_AVOID_TRANSITION_DIST = 0.70

    # Obstacle-avoidance hold persistence (prevent premature snap-back).
    OBSTACLE_AVOID_HOLD_FRAMES_MAX = 60
    OBSTACLE_AVOID_CASCADE_DEPTH = 2

    # Wall-aware detour scoring (prevents choosing detour paths into boundaries).
    OBSTACLE_DETOUR_WALL_PENALTY = 15.0

    # Trap escape: when drone is pinned between obstacle and wall.
    OBSTACLE_TRAP_ESCAPE_GAIN = 1.5

    # Binary Tide boundary override (last-resort wall protection).
    BINARY_TIDE_BOUNDARY_ENABLE = True
    BINARY_TIDE_BOUNDARY_GAIN = 2.5

    # Binary Tide hard safety override (last-resort action replacement).
    BINARY_TIDE_ENABLE = True
    BINARY_TIDE_MARGIN = 0.15
    BINARY_TIDE_THRUST_BOOST = 0.08
    BINARY_TIDE_LATERAL_GAIN = 2.0
    BINARY_TIDE_CLIMB_ACCEL = 3.0
    BINARY_TIDE_BRAKE_GAIN = 0.5
    BINARY_TIDE_HOLD_FRAMES = 6
    BINARY_TIDE_MAX_ROLL_RATE = 0.95
    BINARY_TIDE_MAX_PITCH_RATE = 0.95

    # Startup yaw alignment: hover/rise first, rotate nose to +x, then lock yaw.
    MPC_YAW_ALIGN_ENABLE = True
    MPC_YAW_ALIGN_MIN_FRAMES = 45
    MPC_YAW_ALIGN_MAX_FRAMES = 135
    MPC_YAW_ALIGN_ALT = 0.75
    MPC_YAW_ALIGN_MIN_UP_ACCEL = 0.48
    MPC_YAW_ALIGN_THRESH = 0.05
    MPC_YAW_ALIGN_HOLD_FRAMES = 8
    MPC_YAW_ALIGN_RATE_KP = 1.65
    MPC_YAW_ALIGN_RATE_MAX = 0.48
    MPC_YAW_ALIGN_XY_ACCEL_LIMIT = 0.08
    MPC_YAW_ALIGN_TILT_RAD = 0.020

    # Controller parameters.
    KP_POS = 0.3
    KP_VEL_XY = 0.2
    KP_VEL_Z = 0.3
    MAX_XY_VEL = 0.8
    MAX_Z_VEL = 0.5
    MAX_TILT_RATE = 0.2
    HOVER_BASE_THRUST = 0.0671
    POS_KP_XY = 0.10
    POS_KP_Z = 0.15
    MAX_XY_RATE = 0.25
    MAX_TILT_ANGLE = 0.06

    RISE_POS_KP_XY = 0.0
    RISE_VEL_DAMP_XY = 0.12
    RISE_DESIRED_VZ_GAIN = 0.45
    RISE_THRUST_KP = 0.70
    RISE_MAX_VZ = 0.55
    RISE_MAX_TILT_ANGLE = 0.02
    RISE_TO_HOVER_Z_THRESH = 0.10

    HOVER_STABLE_Z_THRESH = 0.10
    HOVER_POS_KP_XY = 0.20
    HOVER_VEL_DAMP_XY = 0.22
    HOVER_MAX_TILT_ANGLE = 0.08
    HOVER_DESIRED_VZ_GAIN = 0.20
    HOVER_THRUST_KP = 0.45
    HOVER_MAX_VZ = 0.25
    HOVER_MAX_XY_SPEED = 0.25
    HOVER_ENTRY_HOLD_FRAMES = 45
    HOVER_UNSTABLE_MIN_FRAMES = 15
    HOVER_STABLE_XY_SPEED = 0.45
    HOVER_BYPASS_DIST_XY = float("inf")

    ACTION_ROLL_SIGN = -1.0
    ACTION_PITCH_SIGN = -1.0
    ACTION_YAW_SIGN = -1.0
    FORCE_ZERO_ROLL = True
    HEADING_Y_SIGN = -1.0

    ALIGN_YAW_THRESH = 0.06
    ALIGN_Z_THRESH = 0.12
    ALIGN_YAW_RATE_KP = 1.20
    ALIGN_YAW_RATE_MAX = 0.30
    ALIGN_HOLD_FRAMES = 8

    # RISE pitch leveling (拉平俯仰，pitch/yaw 分离约束)
    LEVEL_PITCH_THRESH = 0.01
    LEVEL_PITCH_KP = 1.5
    LEVEL_PITCH_RATE_THRESH = 0.01
    LEVEL_XY_SPEED_THRESH = 0.02

    NO_ROLL_CRUISE_PITCH_KP = 0.60
    NO_ROLL_BRAKE_PITCH_KP = 0.85
    NO_ROLL_PITCH_RATE_KP = 2.40
    NO_ROLL_MAX_PITCH_ANGLE = 0.16
    NO_ROLL_MAX_PITCH_RATE = 0.35
    NO_ROLL_LATERAL_VEL_DAMP = 0.60
    NO_ROLL_FWD_SPEED_KP = 0.55
    NO_ROLL_FWD_SPEED_MAX = 0.95
    NO_ROLL_BRAKE_HOLD_FRAMES = 12

    FLY_DESIRED_VZ_GAIN = 0.22
    FLY_THRUST_KP = 0.45
    FLY_MAX_VZ = 0.40
    FLY_POS_KP_XY = 0.35
    FLY_MAX_XY_SPEED = 0.80
    FLY_BRAKE_DIST_XY = 1.20
    FLY_BRAKE_DECEL = 1.80
    FLY_BRAKE_REVERSE_GAIN = 0.90
    FLY_BRAKE_MAX_TILT_ANGLE = 0.10

    RISE_MAX_XY_SPEED = 0.05

    HOVER_BRAKE_DIST_XY = 0.60
    HOVER_BRAKE_DECEL = 1.40
    HOVER_BRAKE_REVERSE_GAIN = 1.10
    HOVER_BRAKE_MAX_TILT_ANGLE = 0.12

    BRAKE_DEADBAND_DIST_XY = 0.08
    BRAKE_MAX_REVERSE_SPEED = 0.35

    ROUTE_WP_REACHED_DIST_XY = 0.15
    ROUTE_WP_REACHED_DIST_Z = 0.15
    ROUTE_WP_REACHED_SPEED_XY = 0.12

    GOAL_HOVER_DIST_XY = 0.18
    GOAL_HOVER_DIST_Z = 0.18
    GOAL_HOVER_SPEED_XY = 0.15

    # Velocity controller.
    VC_KP_XY = 0.8
    VC_KP_Z = 1.0
    VC_HOVER_OFFSET = 0.0
    VC_MAX_ROLL_PITCH = 0.5

    # Potential field planner.
    PF_ATTRACTIVE_GAIN = 1.0
    PF_REPULSIVE_GAIN = 1.5
    PF_REPULSIVE_RANGE = 0.5
    PF_DAMPING_GAIN = 0.8
    PF_MAX_VELOCITY = 0.5
    PF_BOUNDARY_REPULSIVE_GAIN = 2.0
    PF_BOUNDARY_MARGIN = 0.3

    # Emergency safety.
    SAFETY_RADIUS = 0.25
    EMERGENCY_BACKWARD_SPEED = 1.5
    EMERGENCY_CLIMB_SPEED = 1.0

    # Arena bounds.
    ARENA_X_MIN = 0.0
    ARENA_X_MAX = 5.0
    ARENA_Y_MIN = 0.0
    ARENA_Y_MAX = 5.0
    ARENA_Z_MIN = 0.1
    ARENA_Z_MAX = 3.0

    # Action format.
    MOTOR_MIXING_MODE = False

    # Observation layout (95D).
    OBS_IDX_TARGET_RPOS = [0, 1, 2]
    OBS_IDX_OBSTACLE_RPOS_START = 3
    OBS_IDX_LINEAR_VELOCITY = [27, 28, 29]
    OBS_IDX_ANGULAR_VELOCITY = [30, 31, 32]
    OBS_IDX_ROTATION_MATRIX_START = 33
    OBS_IDX_HOVER_TIMER = 42
    OBS_IDX_OBSTACLE_RADII_START = 43
    OBS_IDX_START_RPOS = [51, 52, 53]
    OBS_IDX_GOAL_RPOS = [54, 55, 56]
    OBS_IDX_PHASE_ONEHOT = [57, 58]
    OBS_IDX_WAYPOINT_RPOS_START = 59
    OBS_IDX_WAYPOINT_VISITED_START = 83
    OBS_IDX_TIME_ENCODING = [91, 92, 93, 94]
    OBSTACLE_MAX_COUNT = 8
